"""Build local WOFF2 blocks using the source font and public web code only.

Build dependencies only: python -m pip install fonttools brotli
Run from any directory: python scripts/build_fonts.py
"""

from collections import defaultdict
from copy import deepcopy
import hashlib
import json
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


ASSETS = Path(__file__).resolve().parents[1] / "web" / "assets"
SOURCE = ASSETS / "NotoSerifCJKjp-Regular.otf"
BLOCK_SIZE = 1024


def variation_sequences(font):
    return {
        (base, selector): glyph
        for table in font["cmap"].tables if table.format == 14
        for selector, entries in table.uvsDict.items()
        for base, glyph in entries
    }


def vertical_mappings(font):
    result = {}
    gsub = font["GSUB"].table
    for feature in gsub.FeatureList.FeatureRecord:
        if feature.FeatureTag not in {"vert", "vrt2"}:
            continue
        mappings = result.setdefault(feature.FeatureTag, set())
        for index in feature.Feature.LookupListIndex:
            for table in gsub.LookupList.Lookup[index].SubTable:
                table = getattr(table, "ExtSubTable", table)
                mappings.update(table.mapping.items())
    return result


def unicode_ranges(codepoints):
    ranges = []
    start = end = None
    for point in sorted(codepoints):
        if end is not None and point == end + 1:
            end = point
            continue
        if start is not None:
            ranges.append(f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}")
        start = end = point
    if start is not None:
        ranges.append(f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}")
    return ",".join(ranges)


def main():
    source = TTFont(SOURCE, lazy=False, recalcTimestamp=False)
    cmap = source.getBestCmap()
    variations = variation_sequences(source)
    vertical = vertical_mappings(source)
    public_sources = [ASSETS.parent / name for name in ("index.html", "app.js", "style.css")]
    common = set(range(0x20, 0x7F))
    for path in public_sources:
        common.update(map(ord, path.read_text(encoding="utf-8")))
    common.intersection_update(cmap)
    blocks = defaultdict(set)
    for point in cmap.keys() - common:
        blocks[point // BLOCK_SIZE].add(point)
    chunks = [("common", common)] + [(f"{block * BLOCK_SIZE:05x}", points) for block, points in sorted(blocks.items())]
    destination = ASSETS / "fonts"
    destination.mkdir(exist_ok=True)
    options = subset.Options()
    options.layout_features = ["*"]
    options.name_IDs = ["*"]
    options.name_languages = ["*"]
    options.glyph_names = True
    options.bidi_closure = False
    options.recalc_timestamp = False
    options.notdef_outline = True
    all_cmap = {}
    all_variations = {}
    css = ["/* Generated by scripts/build_fonts.py; do not edit. */"]
    manifest = []
    for index, (label, points) in enumerate(chunks, 1):
        expected_variations = {key: value for key, value in variations.items() if key[0] in points}
        selectors = {key[1] for key in expected_variations}
        font = deepcopy(source)
        worker = subset.Subsetter(options=options)
        worker.populate(unicodes=points | selectors)
        worker.subset(font)
        font.flavor = "woff2"
        temporary = destination / f"noto-serif-jp-{label}.woff2"
        font.save(temporary)
        digest = hashlib.sha256(temporary.read_bytes()).hexdigest()
        filename = f"noto-serif-jp-{label}-{digest[:12]}.woff2"
        output = destination / filename
        temporary.replace(output)
        with TTFont(output) as check:
            actual_cmap = check.getBestCmap()
            assert actual_cmap == {point: cmap[point] for point in points}, filename
            assert variation_sequences(check) == expected_variations, filename
            actual_vertical = vertical_mappings(check)
            glyphs = set(check.getGlyphOrder())
            for tag, mappings in vertical.items():
                expected = {(a, b) for a, b in mappings if a in glyphs}
                assert actual_vertical.get(tag, set()) == expected, (filename, tag)
            assert "vhea" in check and "vmtx" in check, filename
            all_cmap.update(actual_cmap)
            all_variations.update(variation_sequences(check))
        ranges = unicode_ranges(points | selectors)
        css.append(
            "@font-face {\n  font-family: 'Noto Serif JP';\n"
            f"  src: url('/assets/fonts/{filename}') format('woff2');\n"
            "  font-style: normal;\n  font-weight: 400;\n  font-display: swap;\n"
            f"  unicode-range: {ranges};\n}}"
        )
        manifest.append({"file": filename, "bytes": output.stat().st_size,
                         "sha256": hashlib.sha256(output.read_bytes()).hexdigest(),
                         "unicode_count": len(points), "variation_count": len(expected_variations),
                         "unicode_range": ranges})
        print(f"{index}/{len(chunks)} {filename}: {output.stat().st_size} bytes", flush=True)
    assert all_cmap == cmap
    assert all_variations == variations
    report = {"source": SOURCE.name, "source_bytes": SOURCE.stat().st_size,
              "source_sha256": hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
              "unicode_count": len(cmap), "variation_count": len(variations),
              "common_source_files": [str(path.relative_to(ASSETS.parent)) for path in public_sources],
              "common_unicode_count": len(common), "common_subset_bytes": manifest[0]["bytes"],
              "block_size": BLOCK_SIZE, "subset_bytes": sum(item["bytes"] for item in manifest),
              "checks": {"unicode_mapping_identical": True, "variation_sequences_identical": True,
                         "vertical_substitutions_preserved": True, "vertical_metrics_present": True},
              "subsets": manifest}
    (ASSETS / "noto-serif-subsets.css").write_text("\n\n".join(css) + "\n", encoding="utf-8")
    (ASSETS / "font-subsets.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    current_files = {item["file"] for item in manifest}
    for path in destination.glob("noto-serif-jp-*.woff2"):
        if path.name not in current_files:
            path.unlink()
    print(json.dumps({key: value for key, value in report.items() if key != "subsets"}, indent=2))


if __name__ == "__main__":
    main()
